name: caisoapi-env
channels:
  - defaults
  - conda-forge
dependencies:
  - python=3.10
  - pandas>=1.3.0
  - matplotlib>=3.4.0
  - openpyxl>=3.0.0
  - requests>=2.25.0
  - pip
  - pip:
      - PySimpleGUI>=4.45.0
